Homework 6, Task 1, Кропачева А.М.
martilut/KotlinProjects pull request #20
Opened 2021-04-22 12:54 UTC by martilut

2021-05-02 14:47 UTC, elena-lyulina requested changes
Красивые графики :)

2021-05-02 14:47 UTC, elena-lyulina commented on src/main/kotlin/homework6/GraphApp.kt
> +                            }
можно вынести `val count = ...` перед `when` и вместо двух `when` сделать один, сейчас немного странно смотрится

2021-05-02 14:47 UTC, elena-lyulina commented on src/main/kotlin/homework6/GraphApp.kt
> +                                        alert(Alert.AlertType.WARNING, "Number must be less than 1000")
сообщение не соответствует немного действительности, оно выводится, когда count строго больше 1000, а говорит, что должно быть строго меньше 1000

2021-05-02 14:47 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSort.kt
> +fun IntArray.mergeArrays(left: Int, right: Int, mid: Int) {
вот это хочется тоже многопоточным иметь

2021-05-02 14:47 UTC, elena-lyulina commented on src/main/kotlin/homework6/SortingStatistics.kt
> +fun getStatistics(threadCount: Int): MutableList<Pair<Int, Double>> {
давай вместо Pair<Int, Double> сделаем data class, где будет два аргумента (Int, Double) c осмысленными названиями, так будет легче понимать, что ты там хранишь

2021-05-02 14:47 UTC, elena-lyulina commented on src/main/kotlin/homework6/SortingStatistics.kt
> +object SortingStatistics {
это выглядит очень странно, по идее у каждой переменной должна быть своя цель и в идеале она должна быть одна. Например, переменная, обозначающая, с каким шагом ты будешь увеличивать количество элементов (степень двойки) и сколько раз ты это вообще будешь делать (20), в каких единицах ты считаешь эелементы (в тысячах), в каких единицах ты считаешь время (в биллионах) и так далее. И называть их надо в соответствии с этой целью, а НЕ С ЗНАЧЕНИЕМ, иначе будет очень трудно понимать, что ты имеешь в виду. И если ты где-то в другом месте используешь 1000, ты не должна использовать эту же самую переменную просто потому, что у нее то же самое значение. Вдруг тебе в будущем понадобится изменить ее значение, так как ты решишь измерять элементы теперь не в тысячах, а в десятках. И ВНЕЗАПНО у тебя упадет что-то в том месте, где ты использовала эту переменную как тысячу (например, когда ты в графе проверяешь макс количество потоков)

2021-05-02 14:47 UTC, elena-lyulina commented on src/main/kotlin/homework6/SortingStatistics.kt
> +object SortingStatistics {
еще один комментарий -- не надо лишний раз делать просто файл с набором публичных функций, если это не какие-то повсеместно используемые функции, так как все еще надо следить за инкапсуляцией и не давать кому попало использовать эти функции

2021-05-02 14:47 UTC, elena-lyulina commented on src/main/kotlin/homework6/SortingStatistics.kt
> +object SortingStatistics {
как со всем этим бороться: сделать из всего файла один класс (можно объект), константы сделать приватными свойствами с осмысленными именами (не TWO, TWENTY и т.д., а в соответствии с их функцией), добавить модификаторы доступа к методам, которые не должны использоваться извне и будет отдельная сущность, отвечающая за сбор статистики, у которой извне можно вызвать getStatistic и все, остальное все скрыто

2021-05-02 14:47 UTC, elena-lyulina commented on src/main/kotlin/homework6/GraphApp.kt
> +                                    count > SortingStatistics.THOUSAND ->
давай не использовать SortingStatistics.THOUSAND, которая вообще не об этом (смотри огромный коммент к определению SortingStatistics.THOUSAND), и упавшую с неба 1 как верхнюю и нижнюю границы, а вынесем эти значения в свойства класса, назовем их как-то соответсвующе (minThreadNumber, maxThreadNumber, например) и будем использовать уже их, а не число и чужую константу

2021-05-02 14:47 UTC, elena-lyulina commented on src/main/kotlin/homework6/SortingStatistics.kt
> +        val count = SortingStatistics.TWO.pow(i).toInt()
не уверена, что увеличивание размера массива по степени двойки -- оптимальная стратегия, судя по графику точки в самом начале практически склеиваются и непонятно, что там, а в конце -- между ними слишком большой шаг, мб стоит рассмотреть линейное увеличение?

2021-05-02 14:47 UTC, elena-lyulina commented on src/main/kotlin/homework6/SortingStatistics.kt
> +        val count = SortingStatistics.TWO.pow(i).toInt()
![image](https://user-images.githubusercontent.com/24303332/116816298-10b34800-ab6a-11eb-8ab7-90a440a7e55a.png)

2021-05-02 14:47 UTC, elena-lyulina commented on src/main/kotlin/homework6/GraphApp.kt
> +            }
это выглядит немного странно, у тебя по сути в списке все время один элемент (который ты положила в момент создания linechart) и по сути тебе вообще не обязательно делать это списком (ты и берешь все время нулевой элемент из него)

что можно сделать -- вообще не создавать никаких объектов, а создать просто переменную, в которой хранить как раз действие, которое должно исполниться, когда поменяется count, назовем его, например, onCountChangeAction. Пусть оно будет принимать как раз новый count (Int), таким образом оно будет вот таким: `var onCountChangeAction: (Int) -> Unit`

При этом инициализировать мы его хотим позже, поэтому добавим модификатор [lateinit](https://kotlinlang.org/docs/properties.html#late-initialized-properties-and-variables) 

Тогда при нажатии кнопки ENTER мы будет просто вызывать это действие, передавая ему новый count, а в linechart мы инициализируем это действие, присвоив ему вызов addSeries

2021-05-27 10:47 UTC, elena-lyulina commented on src/main/kotlin/homework6/GraphApp.kt
> +                            }
это как-то не поправилось, поправь, пожалуйста
![image](https://user-images.githubusercontent.com/24303332/119813556-19d9cf80-bef2-11eb-8ee1-70d39e970d65.png)

2021-05-27 11:05 UTC, elena-lyulina requested changes

2021-05-27 11:05 UTC, elena-lyulina commented on src/main/kotlin/homework6/GraphApp.kt
> +    companion object {
а что с порядком элементов? почему методы находятся выше свойств? и companion object тоже не на месте
посмотри на https://kotlinlang.org/docs/coding-conventions.html#class-layout

2021-05-27 11:05 UTC, elena-lyulina commented on src/main/kotlin/homework6/SortingStatistics.kt
> +class SortingStatistics {
вполне можно сделать объектом

2021-05-27 11:05 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorting.kt
> +class MergeSorting {
вот это тоже может быть объектом, чтобы не создавать каждый раз экземпляр класса

2021-05-27 11:05 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorting.kt
> +        }
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/copy-into.html

2021-05-27 11:05 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorting.kt
> +    data class ArrayBorders(val left: Int, val right: Int, val size: Int = right - left + 1)
лучше не делать size аргументом, тогда туда могут передать какое-то совсем неподходящее число
сделай его свойством класса и определи сразу правильным образом, чтобы это точно было размером

2021-05-27 11:05 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorting.kt
> +                    else -> {
а если threadCount < 1?

2021-05-27 11:05 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorting.kt
> +            1 -> sortedArray[finalLeftBorder] = this[currentPart.left]
а если размер < 1?

2021-05-27 11:05 UTC, elena-lyulina commented on src/test/kotlin/homework6/MergeSortKtTest.kt
> +        MergeSorting().mergeSort(input, 1)
хочется многопоточность тоже протестировать)

2021-05-31 20:33 UTC, elena-lyulina requested changes

2021-05-31 20:33 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorting.kt
> +                    threadCount < 1 -> {}
эм, тебе же все равно их надо отсортировать, просто немногопоточно 
поменяй просто условие threadCount == 1 на threadCount <= 1

2021-05-31 20:33 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorting.kt
> +                val leftThread = Thread {
а тут по идее тоже надо проверять, что у тебя больше одного потока доступно в threadCount

2021-06-01 10:49 UTC, martilut commented on src/main/kotlin/homework6/MergeSorting.kt
> +                val leftThread = Thread {
проверяю вот здесь
![image](https://user-images.githubusercontent.com/35008058/120311414-1e322e00-c2e0-11eb-85e3-c4852521f25f.png)

2021-06-01 17:23 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorting.kt
> +                val leftThread = Thread {
хорошо :)

2021-06-01 17:23 UTC, elena-lyulina approved these changes

2021-06-01 17:23 UTC, merged